# Generated by Django 6.0.3 on 2026-03-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('duedate', models.DateField()),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
