# Generated by Django 6.0.3 on 2026-03-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_task_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
